# This image will be published as dspace/dspace
# See https://dspace-labs.github.io/DSpace-Docker-Images/ for usage details
# 
# - tomcat:8
# - ANT 1.10.5
# - maven:latest
# - note: 
# - default tag for branch: dspace/dspace: dspace/dspace:dspace-6_x-jdk8


# Step 1 - Run Ant Deploy
FROM tomcat:8 as ant_build

# Create the initial install deployment using ANT
ENV ANT_VERSION 1.10.5
ENV ANT_HOME /tmp/ant-$ANT_VERSION
ENV PATH $ANT_HOME/bin:$PATH

RUN mkdir $ANT_HOME && \
    wget -qO- "https://www.apache.org/dist/ant/binaries/apache-ant-$ANT_VERSION-bin.tar.gz" | tar -zx --strip-components=1 -C $ANT_HOME

#ADD --chown=dspace . /dspace-installer
ADD . /dspace-installer
WORKDIR /dspace-installer

RUN cp config/docker.cfg config/local.cfg && \
    mkdir /dspace && \
    ant update_configs update_code update_webapps update_solr_indexes

# Step 2 - Run tomcat
# Create a new tomcat image that does not retain the the build directory contents
FROM tomcat:8

# Ant will be embedded in the final container to allow additional deployments
ENV ANT_VERSION 1.10.5
ENV ANT_HOME /tmp/ant-$ANT_VERSION
ENV PATH $ANT_HOME/bin:$PATH

RUN mkdir $ANT_HOME && \
    wget -qO- "https://www.apache.org/dist/ant/binaries/apache-ant-$ANT_VERSION-bin.tar.gz" | tar -zx --strip-components=1 -C $ANT_HOME

COPY --from=ant_build /dspace /dspace
EXPOSE 8080 8009

ENV DSPACE_INSTALL=/dspace
ENV JAVA_OPTS=-Xmx2000m

RUN ln -s $DSPACE_INSTALL/webapps/xmlui   /usr/local/tomcat/webapps/xmlui   && \
    ln -s $DSPACE_INSTALL/webapps/rest    /usr/local/tomcat/webapps/rest    && \
    ln -s $DSPACE_INSTALL/webapps/oai     /usr/local/tomcat/webapps/oai     && \
    ln -s $DSPACE_INSTALL/webapps/rdf     /usr/local/tomcat/webapps/rdf     && \
    ln -s $DSPACE_INSTALL/webapps/swordv2 /usr/local/tomcat/webapps/swordv2