<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.dspace</groupId>
    <artifactId>server-boot</artifactId>
    <name>DSpace Server Webapp:: Executable JAR</name>

    <!--
      A Parent POM that Maven inherits DSpace Default
      POM attributes from.
    -->
    <parent>
        <artifactId>modules</artifactId>
        <groupId>org.dspace</groupId>
        <version>9.4-drum-1-SNAPSHOT</version>
        <relativePath>..</relativePath>
    </parent>

    <properties>
        <!-- This is the path to the root [dspace-src] directory. -->
        <root.basedir>${basedir}/../../..</root.basedir>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.dspace.modules</groupId>
            <artifactId>additions</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dspace.modules</groupId>
            <artifactId>server</artifactId>
            <classifier>classes</classifier>
        </dependency>
        <dependency>
            <groupId>org.dspace</groupId>
            <artifactId>dspace-server-webapp</artifactId>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>org.dspace</groupId>
            <artifactId>dspace-api</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.dspace</groupId>
            <artifactId>dspace-server-webapp</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <version>${spring-security.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path-assert</artifactId>
            <version>${json-path.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Solr Core is only needed for Integration Tests (to run a MockSolrServer) -->
        <!-- The following Solr / Lucene dependencies also support integration tests -->
        <dependency>
            <groupId>org.apache.solr</groupId>
            <artifactId>solr-core</artifactId>
            <version>${solr.client.version}</version>
            <scope>test</scope>
            <exclusions>
                <!-- Newer version brought in by opencsv -->
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-text</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-analyzers-icu</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <!-- UMD Customization -->
            <!--
            By default, Spring Boot generates "BOOT-INF/classpath.idx", used to
            define the Java CLASSPATH when running in Docker, with the jar
            files in alphabetical order.

            The dspace/modules/server module contains overrides of DSpace
            classes in the "dspace-server-webapp" module, and so must appear
            before the dspace-server-webapp" module in the classpath.

            The following unpacks the classes in the "server" module into the
            BOOT-INF/classes directory in the "server-boot.jar", places them
            ahead of all the other jars in the Java CLASSPATH, including those
            in the "dspace-server-webapp" module, forcing the override.

            Note: The classes in the "additions" jar also unpacked.
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>overlay-custom-server-classes</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>org.dspace.modules</groupId>
                                    <artifactId>server</artifactId>
                                    <version>${project.version}</version>
                                    <type>jar</type>
                                    <classifier>classes</classifier>
                                    <outputDirectory>
                                        ${project.build.outputDirectory}
                                    </outputDirectory>
                                    <overWrite>true</overWrite>
                                </artifactItem>
                            </artifactItems>
                            <excludes>
                                META-INF/MANIFEST.MF
                            </excludes>
                        </configuration>
                      </execution>
                </executions>
            </plugin>
            <!-- End UMD Customization -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <!-- UMD Customization -->
                        <!--
                         The "additions and "server" module classes have
                         already been loaded by the customization above, so
                         exclude them from the list of jars.
                        -->
                        <configuration>
                            <excludes>
                                <exclude>
                                    <groupId>org.dspace.modules</groupId>
                                    <artifactId>server</artifactId>
                                    <classifier>classes</classifier>
                                </exclude>
                                <exclude>
                                    <groupId>org.dspace.modules</groupId>
                                    <artifactId>additions</artifactId>
                                </exclude>
                            </excludes>
                        </configuration>
                        <!-- End UMD Customization -->
                    </execution>
            </executions>
            </plugin>
        </plugins>
    </build>
</project>
